### ISSUE TITLE
Documentation!!

### ISSUE THREAD

**Issue by chrisgeary92** [indigotree/atlas#11]
Include a note in the docs about the development having the hugo binary on their computer. Atlas won't run without it.

**Comment by chrisgeary92** [comment]
Also include information about atlas not being a theme.. And not to confuse it as one :)

**Comment by johnrlive** [comment]
Also include info on how to add a new theme without breaking atlas features; gulp, security, better defaults, and redirect features.

**Comment by chrisgeary92** [comment]
@johnrlive adding a theme, which is not supported (and likely never will be), should work if you remove most/all of the files from the `/layouts/partials` and `/layouts/_default` directories & the `/layouts/404.html` file.

It does depend on the particular themes, as some will try to handle your `robots.txt` etc, and this may not work. Which isn't ideal, but as Hugo has no concept of plugins, this sort of stuff happens.

I'll see what I can put together regarding this in the docs. It's not something I want to promote, as that's not the direction/goal of Atlas. However, I appreciate it's something others are likely to do.

By all means, ping me @chrisgeary92 on gophers.slack.com (#hugo team) if you have any questions
