### ISSUE TITLE
Making gulp look for SASS files installed with npm or yarn

### ISSUE THREAD

**Issue by olafghanizadeh** [indigotree/atlas#15]
Hello, 

First of all, this is a lovely starter kit for Hugo + Netlify! Really speeding up my process. For my current website I'm using the Bulma CSS framework and I've installed it with yarn. However, when I try to compile my site I get the following error_
```
{ Error: src/sass/app.scss
Error: File to import not found or unreadable: ~bulma/bulma.
       Parent style sheet: /Users/olafg/Development/hugo/atlas/src/sass/app.scss
        on line 3 of src/sass/app.scss
>> @import "~bulma/bulma";
```

It seems like gulp isn't looking for SASS files in the node_modules folder, is that so?

I realise that this might come down to my limited experience with gulp builds, but it's worth a shot :)

**Comment by chrisgeary92** [comment]
Thanks for your kind words. I believe this is a webpack feature, however it's a great idea so I have added support for it into the gulp builds. I may look at adding webpack at a later date, but for now this works :)

Check #16 for the changes :)
