### ISSUE TITLE
screenshot ? 

### ISSUE THREAD

**Issue by orenmizr** [indigotree/atlas#2]
very hard to know the value of it without  without installing it

**Comment by chrisgeary92** [comment]
There is very little to screenshot as we include minimal HTML, and no CSS out of the box. We don't want to force too much on you, and we definitely don't want to force our choice of CSS framework on you. Atlas includes some nice defaults, a build pipeline, configuration for Netlify & NetlifyCMS, ENV driven robots.txt and more.

I will try to include some extra information in the README as there is no mention of SASS, ES2015 support etc. Perhaps more details about each of the main features would be beneficial too.

You can always [Deploy to Netlify](https://app.netlify.com/start/deploy?repository=https://github.com/indigotree/atlas) with ease if you want to preview it.
