### ISSUE TITLE
Proper URL-handling between local and production builds

### ISSUE THREAD

**Issue by olafghanizadeh** [indigotree/atlas#38]
After having launched a site based on Atlas I found out that Google requires you to have full-path URL's (including protocols) to validate sitemaps. Therefore the `baseURL` can't be set to /. It should be set to the production URL. However, when doing this running atlas with browsersync sets the URL's to production URL. 

I think running the default task "gulp server" should run a command similar to "hugo server" that changes the URL's relative to the environment.

**Comment by crgeary** [comment]
Thanks for raising the issue with the sitemaps, I'll try look into that ASAP, although that might not be for a day or two.

I'm yet to [look into this](https://discourse.gohugo.io/t/correct-baseurl-on-netlify-previews/10429) which may help solve the problem.

The main problems with setting the `baseURL` to the live domain is that it's hard to distinguish the difference between Netlify previews, Netlify branch deploys & the primary website. It's been a while since I looked at the docs for this, so perhaps things have changed.

In the meantime, you could overwrite the `netlify.toml` file to set the `baseURL` for production builds.

Sorry :)

**Comment by moshie** [comment]
This should be fixed now!

If you wouldn't mind merging my PR @crgeary 👍

**Comment by crgeary** [comment]
Merged, thanks both of you for raising it, and fixing it 👍

**Comment by olafghanizadeh** [comment]
So for this to work properly, which URL's do I have to define and where?

**Comment by crgeary** [comment]
Assuming you're using Netlify (as this is heavily integrated with Netlify), then it should just work for you without any changes from you.

The builds make use of the `DEPLOY_PRIME_URL` and the `URL` environment variables that [Netlify makes available](https://www.netlify.com/docs/continuous-deployment/#build-environment-variables) in the build. Your `config.toml` should still be `/` (for localhost), the other sites (production, branches & deploy previews) will be set by Netlify.

Please let me know if you have any issues :)

**Comment by olafghanizadeh** [comment]
Ah, I see. Keep `baseURL` as `/` and then Netlify injects the correct URL on build then?

**Comment by crgeary** [comment]
Exactly that 👍

**Comment by raheems** [comment]
Can anyone confirm that to properly have the URLs in the generated sitemap.xml file, the Netlify build parameters should be like this:

Key: URL
Value: http://www.domain.com

I've done this but the sitemap.xml still does not show the site's actual url.

**Comment by crgeary** [comment]
The Netlify `URL` environment variable should be set for you automatically, based on which your settings are within the Netlify control panel.

It'll either be your *.netlify.com subdomain, or your primary domain as set up within the domain settings of the panel.

I've just checked a site we built recently running Atlas, and the urls within the sitemap appear to be correct.

**Comment by raheems** [comment]
This is how it worked:

Added the deployment parameter:

Key:URL
Value: http://mysite.com

And then modified the build command to following:

hugo -b $URL

**Comment by crgeary** [comment]
Oooh, you're not using Atlas. You probably want to raise these on https://discourse.gohugo.io/ as this Issue is for Atlas issues.

For the record, Atlas handles all of this stuff for you.

**Comment by jonas-sk** [comment]
@crgeary Despite having my primary domain set, my [sitemap](https://pine-maastricht.nl/sitemap.xml) still points at the netlify.com subdomain:

![grafik](https://user-images.githubusercontent.com/7535016/56584473-13265300-65dc-11e9-9f61-c96fab718309.png)

How do I fix this?

**Comment by crgeary** [comment]
Hi @jonas-sk 

Could you try this fix: https://github.com/indigotree/atlas/pull/70

Please let me know how this helps :)
