### ISSUE TITLE
Thoughts on implementing gulp-critical, UnCSS and other front-end optimisations tools

### ISSUE THREAD

**Issue by olafghanizadeh** [indigotree/atlas#43]
Loving Atlas! Great work, speeds up Hugo development a lot. I might try to make a PR for this, but I have to test it first.

If you look at this project:
https://github.com/tr1s/tris-gulp-boilerplate

There are some tools that can be used to further optimise front-end code. I was thinking about testing this on my sites and later creating a PR here, particularly for tools such as gulp-critical and UnCSS.

**Comment by crgeary** [comment]
Thanks for the kind words, and feedback!

I'll take a look at [tr1s/tris-gulp-boilerplate](https://github.com/tr1s/tris-gulp-boilerplate) when I get some spare time. I'd love for Atlas to have even better better performance out of the box.

I would consider waiting for this (https://github.com/gohugoio/hugo/issues/4446) to be PR'd before making too many changes around the assets though, as this might change the way we do things.

Thanks again for the feedback, and of course you're welcome to make a PR to implement some more automated performance wins.

:)

**Comment by olafghanizadeh** [comment]
Ohhh! That PR looks cool. Hugo is great. 

Wordpress frustration lee me here and damn, I’m happy with that!

**Comment by olafghanizadeh** [comment]
Closing this now. Hugo has launched with native SASS processing now :)

**Comment by randallmlough** [comment]
Hugo 0.43 does [support autoprefixer ](https://github.com/gohugoio/hugo/issues/4858). I'm still trying to figure out how to do uncss if that's even possible at the moment.

**Comment by crgeary** [comment]
Oh wow. I didn't realise it has autoprefixer, this is a game changer! Thanks for letting me know. I'll try to refactor this repo asap.

**Comment by bronze** [comment]
@randallmlough hi there man, did u ever figure out how to upport uncss? strugling with this right now.

**Comment by olafghanizadeh** [comment]
@bronze Since Hugo implemented PostCSS support you can do it with the PurgeCSS plugin for PostCSS. Chek this thread on the Hugo forum:
https://discourse.gohugo.io/t/optimizing-css-remove-unused/18863/4

It works, but personally I modified the code so that it doesn't inline my css when building.
