### ISSUE TITLE
Undefined SCSS variables

### ISSUE THREAD

**Issue by hansy** [indigotree/atlas#53]
I keep running into undefined variable errors when running the app. My directory structure inside `src/sass` looks like this:

```
+--base
|    index.scss
|    vars.scss
|    styles.scss
+--app.scss
```

```
// index.scss

@import './vars';
@import './styles';
```

```
// app.scss

@import './base/index';
```

I can eliminate the errors by importing the `vars.scss` file in my other files, but I don't want to keep doing that. Is there a better way to `@import` my vars/mixins just once?

**Comment by crgeary** [comment]
Sorry, I'm not sure I understand what your `index.scss` and `styles.scss` files are used for.

You can include your variables into `app.scss` and they will be available to all the other files you also import into `app.scss` if thats of any help? If not, could you help me understand what you're using for the index/styles files for and I might be able to better help :)

**Comment by crgeary** [comment]
Your `index.scss`, `vars.scss` and `styles.scss` files should all start with an underscore.

See: [Sass Basics > Partials](https://sass-lang.com/guide#topic-4).
