### ISSUE TITLE
Theme Readme Clarification

### ISSUE THREAD

**Issue by javag97** [indigotree/atlas#75]
Hello! Thank you for this project as it has helped get me off the ground in terms of configuration. I would like to share my experience cloning the repo and offer some suggestions in the language of the readme. 

When forking the project, I had issues with getting the `hugo server` command to point to `localhost` due to having an extra leading slash that I ended up removing from the base URL. I tried downloading an existing theme and created my theme to try to solve this problem. After reading the docs more carefully, it became clear what atlas was trying to accomplish, but it took me rereading the docs over and over. 

I am curious how others feel about this change or if others have experienced such an issue. I can try opening a PR and see if y'all like the improvement.

**Comment by crgeary** [comment]
Hey, thanks for the feedback.

If you could create a PR with your proposed changes, that would be fantastic. It's quite possible others have and will have the same issue, so if we can improve then I'm all for it.

**Comment by paulgibbs** [comment]
Sorry @javag97 that no-one looked at your PR in a timely manner. I've merged it now.
